# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: $(vmImage)
  name: 
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Az-Pipelines'
    subscriptionId: '46f98ff8-f6fe-4ad6-bf45-8cd4aca59959'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Az-Pipelines'
    location: 'East US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Validation'
    deploymentName: 'aks_deployment'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
